# Generated by Django 3.2.6 on 2021-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Text of a new question'),
        ),
    ]
